Repository jaydeepukani/PJz6b5MjJ6dKm4KNH9QtqsrP, pull requests merged in 2022-01, with the labels that each got.

#39 Minor Bug fix and Enhancements Done
  app/Http/Controllers/Api/Ayrshare/AyrshareController.php
  app/Http/Controllers/User/PostScheduling/PostSchedulingController.php
  app/Models/AyrUserProfile.php
  database/migrations/2022_01_05_100650_create_ayr_user_profiles_table.php
  resources/views/welcome.blade.php
  routes/web.php
  storage/client_secret_337384872514-7ocj11buq2utqe9l7he65hsqlmuhht7f.apps.googleusercontent.com.json
  storage/client_secret_780792244822-f77ic8f4g5hi1eu75p8dm86cqkvac834.apps.googleusercontent.com.json
  storage/client_secret_840868942685-1h6ul3vl2hspfh91smjag8ufhelbct8v.apps.googleusercontent.com.json
Labels: bug, enhancement

#41 Added Missing Include in common.php
  app/Http/Controllers/CommonController.php
Labels: missing

#45 Added 404 not found page
  resources/views/errors/404.blade.php
Labels: enhancement

#46 Minor bug Fixes in CommonController
  app/Http/Controllers/CommonController.php
  resources/views/user/analyze/youtube/overview.blade.php
  resources/views/user/analyze/youtube/videos.blade.php
Labels: bug
